### ISSUE TITLE
Обработать замечания к коммитам

### ISSUE THREAD

**Issue by kuritsynk** [polinavinar/test#2]
См. комментарии в https://github.com/polinavinar/test/commits/master

**Comment by kuritsynk** [comment]
После решения (закрытия) комментариев и коммита нового кода, устраняющего недостатки, закрыть эту задачу.
Исправляющие коммиты должны ссылаться на этот issue.

**Comment by polinavinar** [comment]
в первый раз, выполнила первый коммит, но загрузила неверно.
